version: "2.13"

services:
  pet_clinic:
    container_name: pet-clinic
    image: javabeanstack/pet_clinic:v1
    restart: on-failure
    ports:
      - 8083:8082
    volumes:
      - type: volume
        source: pet_clinic_volume
        target: /usr/pet_clinic_volume
        volume:
          nocopy: true
volumes:
  pet_clinic_volume:
